name: milkymo
version: 1.0.0+1
publish_to: none
description: MilkyMo app using flutter. This is for milk collection center in
  digital recording of milk weighing results.
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.7
  flutter_screenutil: ^5.8.4
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  freezed_annotation: ^2.4.1
  get: 4.6.6
  googleapis: ^13.0.0
  googleapis_auth: ^1.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  iconsax: ^0.0.8
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  otp_text_field: ^1.1.3
  path_provider: ^2.1.2
  popover: ^0.3.0
  shimmer: ^3.0.0
  skeletonizer: ^1.1.2+1
  supabase_flutter: ^2.3.3
  table_calendar: ^3.0.9
  velocity_x: ^4.1.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
